### ISSUE TITLE
Discussion: Approaches for uploading stuff

### ISSUE THREAD

**Issue by hemangsk** [SDC-USICT/Recruitment_Portal#26]

**Comment by surender7790** [comment]
https://stackoverflow.com/questions/15772394/how-to-upload-display-and-save-images-using-node-js-and-express

we can try above solution. Its very easy. changes need to be done according to express 4.x @hemangsk

**Comment by hemangsk** [comment]
This is awesome. We can also allow users to upload PDF/word etc with this, like if they want to upload their resume and stuff.

**Comment by surender7790** [comment]
👍 That will be great.

**Comment by surender7790** [comment]
How are you going to send form data. Using services in angularJs or directly from the form using ng-submit.

**Comment by hemangsk** [comment]
folowing angular service with ng submit from
http://tutsnare.com/post-form-data-using-angularjs/

On Jul 1, 2017 8:29 AM, "Surender kumar" <notifications@github.com> wrote:

>

> How are you going to send form data. Using services in angularJs or
directly from the form using ng-submit.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/SDC-USICT/Recruitment_Portal/issues/26#issuecomment-312406381>,
or mute the thread

**Comment by hemangsk** [comment]
East or west, multer is the best.
