### ISSUE TITLE
Final email shouldn't be sent if Application Transaction was unsuccessful

### ISSUE THREAD

**Issue by hemangsk** [SDC-USICT/Recruitment_Portal#68]

**Comment by surender7790** [comment]
It will only be send when  new application is created in table candidates_2017

**Comment by surender7790** [comment]
@hemangsk

**Comment by hemangsk** [comment]
@surender7790 once new application is created, and if user updates that entry in candidates_2017, then I think we can modify the mail content as 'you application has been updated' etc

**Comment by surender7790** [comment]
@hemangsk  yes that can also be implemented. Simple mail will be sent to the user. About details updated.

**Comment by hemangsk** [comment]
🤘  👍  👍

**Comment by surender7790** [comment]
Cool. 👍 😎
