### ISSUE TITLE
Add login model

### ISSUE THREAD

**Issue by hemangsk** [SDC-USICT/Recruitment_Portal#7]
We are using passport.js cc @surender7790

**Comment by surender7790** [comment]
There is no need to create separate models for login and signup @hemangsk 
only one model named user.js can be used instead for both login and signup.

**Comment by hemangsk** [comment]
superawesome,  @surender7790 lets get the stuff merged into master!!! 🎉

**Comment by surender7790** [comment]
Ok but let me brush up the things. I am still struggling with my router problem. I will let you know when I am ready to merge @hemangsk

**Comment by surender7790** [comment]
Login model is not required as we accomplish the same using only one model named user.js 👍
