### ISSUE TITLE
frontend: Replace mapper() with angular.extend

### ISSUE THREAD

**Issue by hemangsk** [SDC-USICT/Recruitment_Portal#77]

**Comment by stofolus** [comment]
I'm pretty sure this wont work, I've looked at the `mapper` method in `dashboard.js` so let me know if that was the wrong one. `angular.extend` takes two objects and merges them. The mapper method seems to return a renamed subset of candidate values.

As you can see these methods are not interchangeable or even close in functionality

**Comment by devesh-verma** [comment]
@hemangsk Hey if you can provide me more info regarding this I would like to work on this.

**Comment by hemangsk** [comment]
@stofolus Yes right these methods don't seem interchangeable. Thanks a lot for pointing out the mistake on our side. Actually what we want to achieve is that removing the huge mapper function and to use the JSON object directly which is obtained from Backend. So I'll close the issue as we are planning to rephrase the issue in better manner and then post it here for incoming Developers. :) Thanks again.
